### ISSUE TITLE
region_cache crashes when Redis is unavailable

### ISSUE THREAD

**Issue by stumpc** [jheard-tw/region_cache#2]
* region_cache version: 0.2.5
* Python version: 3.6.5
* Operating System: Ubuntu 16.04.02

### Description

region_cache does not have any fallback when it fails to connect to Redis, which is problematic when doing things like initializing app scope to import it into my pytests, as having a Redis connection isn't strictly necessary there.  It would be good to have this be able to be keyed off of an environment variable as well.  Something like `REGION_CACHE_LOCAL` or the like.

### What I Did

Tried to use region_cache without a stable connection to Redis available.

**Comment by jheard-tw** [comment]
The new release should fix this.  It instead logs the issue.  You will still get key errors, etc, which will have to be handled, as the backend is not there, therefore no keys exist in the cache.
